# Generated by Django 5.2.6 on 2025-09-18 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LenderPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pool_type', models.CharField(choices=[('stablecoin', 'Stablecoin Pool'), ('native', 'Native Token Pool')], max_length=50)),
                ('description', models.TextField()),
                ('token_address', models.CharField(max_length=255)),
                ('apy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_liquidity', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('available_liquidity', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('min_deposit', models.DecimalField(decimal_places=18, max_digits=36)),
                ('lock_period_days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lender_pools',
            },
        ),
        migrations.CreateModel(
            name='LenderDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('shares', models.DecimalField(decimal_places=18, max_digits=36)),
                ('deposit_tx_hash', models.CharField(max_length=255)),
                ('unlocked_at', models.DateTimeField()),
                ('withdrawn', models.BooleanField(default=False)),
                ('withdraw_tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='lenders.lenderpool')),
            ],
            options={
                'db_table': 'lender_deposits',
            },
        ),
        migrations.CreateModel(
            name='PoolAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('allocation_tx_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_allocations', to='loans.loan')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='lenders.lenderpool')),
            ],
            options={
                'db_table': 'pool_allocations',
            },
        ),
    ]
